### ISSUE TITLE
Remove pycache file

### ISSUE THREAD

**Issue by amitc005** [GaganSingh11/social-media-api-fastapi#1]
Problem:
.pycache files are being tracked by git.

Resolve:
Add .pycache and .pyc file in git ignore file.

**Comment by GaganSingh11** [comment]
__pychache__ directory addeed to .gitignore

**Comment by achavhanblackline** [comment]
Perfect! Can you please close this issue?

**Comment by amitc005** [comment]
Closing this ticket.
